/*
export const SET_FOLLOWER_USERS = 'SET_FOLLOWER_USERS';
export const CLEAR_FOLLOWERS = 'CLEAR_FOLLOWERS';
export const SET_FOLLOWING_USERS = 'SET_FOLLOWING_USERS';
export const CLEAR_FOLLOWING = 'CLEAR_FOLLOWING';
*/
export const SET_PEOPLE_SEARCH = 'SET_PEOPLE_SEARCH';
export const CLEAR_PEOPLE_SEARCH = 'CLEAR_PEOPLE_SEARCH';
